version: '3.8'

services:
  dataservice:
    build: ./dataservice
    volumes:
      - dbdata:/data
    networks:
      - backend
    expose:
      - "5000"

  webserver:
    build: ./webserver
    ports:
      - "8080:5000"
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
    internal: true
