version: '3.8'

services:
  dataservice:
    build: ./dataservice
    volumes:
      - dbdata:/data
    networks:
      - backstage

  webserver:
    build: ./webserver
    ports:
      - "8888:5000"
    networks:
      - public
      - backstage
    expose:
      - "5000"

volumes:
  dbdata:

networks:
  public:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1
  backstage:
    internal: true